multiple_payment_methods:
  description: "Allow multiple payment methods per customer"
  owners: ["@lovrocolic", "@mariohd"]

postgres_enriched_events:
  description: "Turn on events pre-enrichement for organizations using the PG event store"
  owners: ["@vincent-pochet"]

enriched_events_aggregation:
  description: "Use the enriched events store for aggregation queries in ClickHouse"
  owners: ["@vincent-pochet"]

wallet_traceability:
  description: "Enable wallet traceability on newly created wallets"
  owners: ["@groyoh", "@D1353L"]
