default: &default
  adapter: postgresql

development:
  primary:
    <<: *default
    host: db
    username: lago
    password: changeme
    database: lago
    port: 5432
  events:
    <<: *default
    host: db
    username: lago
    password: changeme
    database: lago
    port: 5432
  clickhouse:
    adapter: clickhouse
    database: default
    host: clickhouse
    port: 8123
    username: default
    password: default
    migrations_paths: db/clickhouse_migrate
    debug: true
    database_tasks: <% if ENV['LAGO_CLICKHOUSE_MIGRATIONS_ENABLED'].present? %> true <% else %> false <% end %>
    schema_dump: false

test:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_TEST_URL'].presence || ENV['DATABASE_URL'] %>
    schema_dump: <% if ENV['LAGO_DISABLE_SCHEMA_DUMP'].present? %> false <% else %> structure.sql <% end %>
  events:
    <<: *default
    url: <%= ENV['DATABASE_TEST_URL'].presence || ENV['DATABASE_URL'] %>
    schema_dump: false
  clickhouse:
    adapter: clickhouse
    database: <%= ENV.fetch('LAGO_CLICKHOUSE_DATABASE', 'default_test') %>
    host: <%= ENV.fetch('LAGO_CLICKHOUSE_HOST', 'clickhouse') %>
    port: <%= ENV.fetch('LAGO_CLICKHOUSE_PORT', 8123) %>
    username: <%= ENV.fetch('LAGO_CLICKHOUSE_USERNAME', 'default') %>
    password: <%= ENV.fetch('LAGO_CLICKHOUSE_PASSWORD', 'default') %>
    migrations_paths: db/clickhouse_migrate
    debug: true
    database_tasks: <% if ENV['LAGO_CLICKHOUSE_MIGRATIONS_ENABLED'].present? %> true <% else %> false <% end %>
    schema_dump: false

staging:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
    pool: <%= ENV.fetch('DATABASE_POOL', 10) %>
  events:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
    pool: <%= ENV.fetch('DATABASE_POOL', 10) %>
    database_tasks: false
  clickhouse:
    adapter: clickhouse
    database: <%= ENV['LAGO_CLICKHOUSE_DATABASE'] %>
    host: <%= ENV['LAGO_CLICKHOUSE_HOST'] %>
    port: <%= ENV.fetch('LAGO_CLICKHOUSE_PORT', 8123) %>
    username: <%= ENV['LAGO_CLICKHOUSE_USERNAME'] %>
    password: <%= ENV['LAGO_CLICKHOUSE_PASSWORD'] %>
    migrations_paths: db/clickhouse_migrate
    debug: false
    database_tasks: <% if ENV['LAGO_CLICKHOUSE_MIGRATIONS_ENABLED'].present? %> true <% else %> false <% end %>

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
    pool: <%= ENV.fetch('DATABASE_POOL', 10) %>
    prepared_statements: <%= ENV.fetch('DATABASE_PREPARED_STATEMENTS', true) %>
    schema_search_path: <%= ENV.fetch('POSTGRES_SCHEMA', 'public') %>
  events:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
    pool: <%= ENV.fetch('DATABASE_POOL', 10) %>
    prepared_statements: <%= ENV.fetch('DATABASE_PREPARED_STATEMENTS', true) %>
    schema_search_path: <%= ENV.fetch('POSTGRES_SCHEMA', 'public') %>
    database_tasks: false
  clickhouse:
    adapter: clickhouse
    database: <%= ENV['LAGO_CLICKHOUSE_DATABASE'] %>
    host: <%= ENV['LAGO_CLICKHOUSE_HOST'] %>
    port: <%= ENV.fetch('LAGO_CLICKHOUSE_PORT', 8123) %>
    pool: <%= ENV.fetch('DATABASE_POOL', 10) %>
    username: <%= ENV['LAGO_CLICKHOUSE_USERNAME'] %>
    password: <%= ENV['LAGO_CLICKHOUSE_PASSWORD'] %>
    ssl: <%= ENV.fetch('LAGO_CLICKHOUSE_SSL', false) %>
    migrations_paths: db/clickhouse_migrate
    debug: false
    database_tasks: <% if ENV['LAGO_CLICKHOUSE_MIGRATIONS_ENABLED'].present? %> true <% else %> false <% end %>
