---
analytics:
  view:
billable_metrics:
  view:
  create:
  update:
  delete:
plans:
  view: true
  create:
  update:
  delete:
addons:
  view: true
  create:
  update:
  delete:
coupons:
  view: true
  create:
  update:
  delete:
  attach:
  detach:
customers:
  view: true
  create:
  update:
  delete:
subscriptions:
  view: true
  create:
  update:
wallets:
  create:
  update:
  top_up:
  terminate:
invoices:
  view: true
  send: true
  update: true
  void: true
  create:
  export: true
draft_invoices:
  update: true
credit_notes:
  view: true
  create: true
  update: true
  void: true
customer_settings:
  view: true
  update:
    tax_rates: true
    payment_terms: true
    grace_period: true
    lang: true
developers:
  manage:
  keys:
    manage:
organization:
  view:
  update:
  invoices:
    view:
    update:
  taxes:
    view:
    update:
  emails:
    view:
    update:
  integrations:
    view:
    create:
    update:
    delete:
  members:
    view:
    create:
    update:
    delete:
