---
audit_logs:
  view: true
authentication_methods:
  view: true
  update: true
analytics:
  overdue_balances:
    view:
  view:
billable_metrics:
  view:
  create:
  update:
  delete:
features:
  view:
  create:
  update:
  delete:
data_api:
  view:
plans:
  view: true
  create:
  update:
  delete:
pricing_units:
  view:
  create:
  update:
ai_conversations:
  view: true
  create: true
addons:
  view: true
  create:
  update:
  delete:
coupons:
  view: true
  create:
  update:
  delete:
  attach:
  detach:
customers:
  view: true
  create:
  update:
  delete:
dunning_campaigns:
  view:
  create:
  update:
  delete:
invoice_custom_sections:
  view: true
  create:
  update:
  delete:
subscriptions:
  view: true
  create:
  update:
wallets:
  create:
  update:
  top_up:
  terminate:
invoices:
  view: true
  send: true
  update: true
  void: true
  create:
  export: true
draft_invoices:
  update: true
credit_notes:
  view: true
  create: true
  update: true
  void: true
  export: true
customer_settings:
  view: true
  update:
    tax_rates: true
    payment_terms: true
    grace_period: true
    lang: true
developers:
  manage:
  keys:
    manage:
organization:
  view:
  update:
  invoices:
    view:
    update:
  taxes:
    view:
    update:
  emails:
    view:
    update:
  integrations:
    view:
    create:
    update:
    delete:
  members:
    view:
    create:
    update:
    delete:
billing_entities:
  view:
  create:
  update:
  delete:
  invoices:
    view:
    update:
  taxes:
    view:
    update:
  emails:
    view:
    update:
  dunning_campaigns:
    update:
payment_requests:
  view: true
  create:
payments:
  view: true
  create:
payment_methods:
  view: true
  create:
  update:
  delete:
