---
audit_logs:
  view: false
authentication_methods:
  view: false
  update: false
analytics:
  overdue_balances:
    view: true
  view: true
billable_metrics:
  view: false
  create: false
  update: false
  delete: false
data_api:
  view: true
plans:
  create: false
  update: false
  delete: false
pricing_units:
  view: true
  create: false
  update: false
ai_conversations:
  view: true
  create: true
addons:
  create: false
  update: false
  delete: false
coupons:
  create: false
  update: false
  delete: false
  attach: false
  detach: false
customers:
  create: false
  update: false
  delete: false
dunning_campaigns:
  view: true
  create: true
  update: true
  delete: true
invoice_custom_sections:
  create: true
  update: true
  delete: true
subscriptions:
  create: false
  update: false
wallets:
  create: false
  update: false
  top_up: false
  terminate: false
invoices:
  create: true
developers:
  manage: false
  keys:
    manage: false
organization:
  view: true
  update: true
  invoices:
    view: true
    update: true
  taxes:
    view: false
    update: false
  emails:
    view: false
    update: false
  integrations:
    view: true
    create: true
    update: true
    delete: true
  members:
    view: false
    create: false
    update: false
    delete: false
billing_entities:
  view: true
  create: true
  update: true
  delete: true
  invoices:
    view: true
    update: true
  taxes:
    view: true
    update: true
  emails:
    view: true
    update: true
  dunning_campaigns:
    update: true
payment_requests:
  view: true
  create: true
payments:
  view: true
  create: true
