concurrency: <%= ENV.fetch('SIDEKIQ_CONCURRENCY', 10) %>
timeout: 25
retry: 1
queues:
  - billing
  - billing_low_priority

production:
  concurrency: <%= ENV.fetch('SIDEKIQ_CONCURRENCY', 5) %>
staging:
  concurrency: 10
