name: "Lago Internal"
on:
  push:
    branches:
      - main
jobs:
  lago-internal:
    name: Lago Internal
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN}}
          event-type: api-push-main
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'